FROM docker.io/library/rust:1.67.1-alpine3.17
RUN rustup toolchain install \
	1.66.1-aarch64-unknown-linux-musl \
	1.65.0-x86_64-unknown-linux-musl \
	1.60.0-aarch64-apple-darwin \
	1.64.0-x86_64-apple-darwin \
	1.50.0-x86_64-unknown-linux-gnu \
	1.63.0-aarch64-unknown-linux-gnu \
	1.51.0-x86_64-unknown-linux-musl \
	1.49.0-x86_64-unknown-linux-musl 
	